"""
Multi-language support for the application.
Supports: Arabic (ar), French (fr), English (en)
"""

LANGUAGES = {
    "ar": "العربية",
    "fr": "Français",
    "en": "English",
}

TRANSLATIONS = {
    "ar": {
        "sales": "البيع",
        "products": "المنتجات",
        "analytics": "التحاليل",
        "notifications": "السلع المنفذة",
        "settings": "الإعدادات",
        "pos": "نقطة البيع",
        "barcode_scan": "الباركود / اسم المنتج",
        "search": "بحث",
        "scan_hint": "وصّل جهاز الباركود واقرأ القطعة مباشرة — أو اكتب الاسم/الباركود يدوياً",
        "recent_sales": "آخر المبيعات اليوم",
        "time": "الوقت",
        "product": "المنتج",
        "quantity": "الكمية",
        "price": "السعر",
        "total": "الإجمالي",
        "profit": "الربح",
        "scan_product": "امسح باركود المنتج أو ابحث عنه بالاسم",
        "category": "الفئة",
        "barcode": "الباركود",
        "sell_price": "سعر البيع",
        "stock": "المخزون",
        "piece": "قطعة",
        "qty_label": "الكمية:",
        "empty_stock": "المخزون فارغ",
        "confirm_sale": "تأكيد البيع",
        "not_found": "لم يُعثر على منتج",
        "choose_product": "اختر المنتج:",
        "error": "خطأ",
        "invalid_qty": "أدخل كمية صحيحة",
        "sale_error": "خطأ في البيع",
        "product_added": "تمت إضافة المنتج بنجاح",
        "barcode_exists": "الباركود مستخدم مسبقاً",
        "product_updated": "تم تحديث المنتج",
        "product_deleted": "تم حذف المنتج",
        "product_name_req": "الاسم مطلوب",
        "data_error": "خطأ في البيانات",
        "success": "نجاح",
        "selled": "تم البيع",
        "admin_mode": "وضعية المسؤول",
        "user_mode": "وضعية المستخدم",
        "switch_to_admin": "التبديل إلى المسؤول",
        "switch_to_user": "التبديل إلى المستخدم",
        "enter_password": "أدخل كلمة المرور",
        "password": "كلمة المرور",
        "cancel": "إلغاء",
        "wrong_password": "كلمة المرور غير صحيحة",
        "current_account": "الحساب الحالي",
        "admin": "Admin",
        "user": "بائع",
        "dark": "داكن",
        "light": "فاتح",
        "alerts": "منتجات تحتاج تزويد",
        "settings_title": "الإعدادات",
        "appearance": "المظهر",
        "theme_mode": "الوضع:",
        "account_settings": "بيانات الحساب",
        "shop_name_label": "اسم المحل",
        "currency_label": "العملة",
        "low_stock_label": "الحد الأدنى للتنبيه",
        "account_type": "نوع الحساب",
        "language": "اللغة",
        "save_settings": "حفظ الإعدادات",
        "about_program": "عن البرنامج",
        "program_name": "نظام المبيعات المتكامل",
        "version": "الإصدار 1.0",
        "appearance_saved": "المظهر",
        "appearance_hint": "سيتم تطبيق الوضع عند إعادة تشغيل البرنامج",
        "settings_saved": "نجاح",
        "settings_saved_msg": "تم حفظ الإعدادات",
        "password_required": "مطلوب",
        "admin_password": "كلمة مرور المسؤول",
        "change_password": "تغيير كلمة المرور",
        "current_password_label": "كلمة المرور الحالية *",
        "new_password_label": "كلمة المرور الجديدة *",
        "confirm_password_label": "تأكيد كلمة المرور الجديدة *",
        "wrong_current_password": "كلمة المرور الحالية غير صحيحة",
        "passwords_dont_match": "كلمات المرور غير متطابقة",
        "password_changed": "تم تغيير كلمة المرور",
        "admin_restricted": "هذه الميزة متاحة للمسؤول فقط",
        "manage_products": "إدارة المنتجات",
        "add": "إضافة",
        "edit": "تعديل",
        "delete": "حذف",
        "clear": "تفريغ",
        "clear_logs": "تفريغ السجل",
        "save": "حفظ",
        "back": "تراجع",
        "confirm": "تأكيد",
        "product_data": "بيانات المنتج",
        "name_label": "الاسم *",
        "barcode_label": "الباركود",
        "category_label": "الفئة",
        "buy_price_label": "سعر الشراء *",
        "sell_price_label": "سعر البيع *",
        "quantity_label": "الكمية *",
        "min_stock_label": "الحد الأدنى",
        "buy_price": "سعر الشراء",
        "confirm_delete": "تأكيد الحذف",
        "delete_product_confirm": "هل تريد حذف هذا المنتج؟",
        "select_product_first": "اختر منتجاً أولاً",
        "alert": "تنبيه",
        "year": "السنة:",
        "refresh": "تحديث",
        "export_pdf": "تصدير PDF",
        "today_revenue": "مبيعات اليوم",
        "today_profit": "أرباح اليوم",
        "month_revenue": "مبيعات الشهر",
        "month_profit": "أرباح الشهر",
        "total_products": "إجمالي المنتجات",
        "analytics_title": "التحاليل والمخططات",
        "matplotlib_missing": "matplotlib غير مثبت",
        "reportlab_missing": "reportlab غير مثبت",
        "install_hint": "pip install reportlab --break-system-packages",
        "save_report": "حفظ التقرير",
        "report_exported": "تم تصدير التقرير",
        "report_error": "خطأ",
        "report": "تقرير",
        "delete_year": "حذف بيانات السنة",
        "delete_year_confirm": "هل تريد حذف جميع مبيعات هذه السنة؟",
        "admin_required": "مطلوب صلاحية المسؤول",
        "barcode_placeholder": "أدخل الباركود هنا...",
        "confirm_delete_sale": "هل أنت متأكد من إلغاء هذه المبيعة؟ (سيتم استرجاع السلعة للمخزون)",
        "accent_color_label": "لون السمة:",
        "undo": "إلغاء المبيعة",
        "delete_sale_confirm": "هل تريد حذف هذه المبيعة من السجل فقط؟ (لن يتم استرجاع السلعة للمخزون)",
        "add_to_cart": "إضافة للسلة",
        "cart_title": "سلة المشتريات",
        "empty_cart": "السلة فارغة",
        "confirm_bulk_sale": "تأكيد عملية البيع",
        "clear_cart_btn": "تفريغ السلة",
        "restart_required": "إعادة التشغيل مطلوبة",
        "restart_msg": "يرجى إعادة تشغيل التطبيق لتطبيق الثيم الجديد بشكل كامل.",
        "restart_now": "إعادة التشغيل الآن",
        "later": "لاحقاً",
        "ok": "تم",
        "select_item_hint": "اختر منتجاً أو مبيعة لعرض التفاصيل",
        "no_data": "لا توجد بيانات بعد",
        "top_selling_title": "الأكثر مبيعاً (كمية)",
        "most_profitable_title": "الأكثر ربحاً",
        "search_placeholder": "بحث عن منتج...",
        "my_clients": "زبائني",
        "credit": "الديون",
        "add_customer": "إضافة زبون",
        "customer_name": "اسم الزبون",
        "customer": "الزبون",
        "sell_on_credit": "بيع بالدين",
        "unpaid": "غير مدفوع",
        "paid": "مدفوع",
        "debt_details": "تفاصيل الدين",
        "confirm_credit_sale": "تأكيد البيع بالدين",
        "pay": "تسديد",
        "phone": "رقم الهاتف",
        "status": "الحالة",
        "refilled": "تم تزويد المخزون",
        "low_stock": "مخزون منخفض",
        "bar_chart": "مخطط أعمدة",
        "line_chart": "مخطط منحنى",
        "revenue_chart": "إحصائيات العوائد السنوية",
        "profit_chart": "إحصائيات الأرباح السنوية",
    },
    "fr": {
        "sales": "Ventes",
        "products": "Produits",
        "analytics": "Analyses",
        "notifications": "Alertes",
        "settings": "Paramètres",
        "pos": "Point de Vente",
        "barcode_scan": "Code-barres / Nom du produit",
        "search": "Recherche",
        "scan_hint": "Connectez le lecteur de codes-barres et scannez — ou tapez le nom/code manuellement",
        "recent_sales": "Dernières ventes du jour",
        "time": "Heure",
        "product": "Produit",
        "quantity": "Quantité",
        "price": "Prix",
        "total": "Total",
        "profit": "Profit",
        "scan_product": "Scannez le code-barres ou recherchez par nom",
        "category": "Catégorie",
        "barcode": "Code-barres",
        "sell_price": "Prix de vente",
        "stock": "Stock",
        "piece": "pièce",
        "qty_label": "Quantité :",
        "empty_stock": "Stock vide",
        "confirm_sale": "Confirmer la vente",
        "not_found": "Produit non trouvé",
        "choose_product": "Choisir le produit :",
        "error": "Erreur",
        "invalid_qty": "Entrez une quantité valide",
        "sale_error": "Erreur de vente",
        "product_added": "Produit ajouté avec succès",
        "barcode_exists": "Code-barres déjà utilisé",
        "product_updated": "Produit mis à jour",
        "product_deleted": "Produit supprimé",
        "product_name_req": "Le nom est requis",
        "data_error": "Erreur de données",
        "success": "Succès",
        "selled": "Vendu",
        "admin_mode": "Mode Administrateur",
        "user_mode": "Mode Utilisateur",
        "switch_to_admin": "Passer à Administrateur",
        "switch_to_user": "Passer à Utilisateur",
        "enter_password": "Entrez le mot de passe",
        "password": "Mot de passe",
        "cancel": "Annuler",
        "wrong_password": "Mot de passe incorrect",
        "current_account": "Compte actuel",
        "admin": "Admin",
        "user": "Vendeur",
        "dark": "Sombre",
        "light": "Clair",
        "alerts": "Produits à réapprovisionner",
        "settings_title": "Paramètres",
        "appearance": "Apparence",
        "theme_mode": "Mode :",
        "account_settings": "Données du compte",
        "shop_name_label": "Nom du magasin",
        "currency_label": "Devise",
        "low_stock_label": "Seuil d'alerte",
        "account_type": "Type de compte",
        "language": "Langue",
        "save_settings": "Enregistrer",
        "about_program": "À propos",
        "program_name": "Gestion de Magasin",
        "version": "Version 1.0",
        "appearance_saved": "Apparence",
        "appearance_hint": "Le mode sera appliqué au redémarrage",
        "settings_saved": "Succès",
        "settings_saved_msg": "Paramètres enregistrés",
        "password_required": "Requis",
        "admin_password": "Mot de passe admin",
        "change_password": "Changer le mot de passe",
        "current_password_label": "Mot de passe actuel *",
        "new_password_label": "Nouveau mot de passe *",
        "confirm_password_label": "Confirmer nouveau mot de passe *",
        "wrong_current_password": "Mot de passe actuel incorrect",
        "passwords_dont_match": "Les mots de passe ne correspondent pas",
        "password_changed": "Mot de passe changé",
        "admin_restricted": "Cette fonctionnalité est réservée à l'administrateur",
        "manage_products": "Gestion des produits",
        "add": "Ajouter",
        "edit": "Modifier",
        "delete": "Supprimer",
        "clear": "Vider",
        "clear_logs": "Vider le journal",
        "save": "Enregistrer",
        "back": "Quitter",
        "confirm": "Confirmer",
        "product_data": "Données du produit",
        "name_label": "Nom *",
        "barcode_label": "Code-barres",
        "category_label": "Catégorie",
        "buy_price_label": "Prix d'achat *",
        "sell_price_label": "Prix de vente *",
        "quantity_label": "Quantité *",
        "min_stock_label": "Stock minimum",
        "buy_price": "Prix d'achat",
        "confirm_delete": "Confirmer la suppression",
        "delete_product_confirm": "Voulez-vous supprimer ce produit ?",
        "select_product_first": "Sélectionnez un produit d'abord",
        "alert": "Alerte",
        "year": "Année :",
        "refresh": "Actualiser",
        "export_pdf": "Exporter PDF",
        "today_revenue": "Ventes du jour",
        "today_profit": "Profits du jour",
        "month_revenue": "Ventes du mois",
        "month_profit": "Profits du mois",
        "total_products": "Total des produits",
        "analytics_title": "Analyses et graphiques",
        "matplotlib_missing": "matplotlib non installé",
        "reportlab_missing": "reportlab non installé",
        "install_hint": "pip install reportlab --break-system-packages",
        "save_report": "Enregistrer le rapport",
        "report_exported": "Rapport exporté",
        "report_error": "Erreur",
        "report": "Rapport",
        "delete_year": "Supprimer l'année",
        "delete_year_confirm": "Voulez-vous supprimer toutes les ventes de cette année ?",
        "admin_required": "Accès administrateur requis",
        "barcode_placeholder": "Entrez le code-barres ici...",
        "confirm_delete_sale": "Êtes-vous sûr de vouloir annuler cette vente ? (Le stock sera restauré)",
        "accent_color_label": "Couleur d'accent :",
        "undo": "Annuler la vente",
        "delete_sale_confirm": "Voulez-vous supprimer cette vente de l'historique uniquement ? (Le stock ne sera pas restauré)",
        "add_to_cart": "Ajouter au panier",
        "cart_title": "Panier",
        "empty_cart": "Le panier est vide",
        "confirm_bulk_sale": "Confirmer la vente",
        "clear_cart_btn": "Vider le panier",
        "restart_required": "Redémarrage requis",
        "restart_msg": "Veuillez redémarrer l'application pour appliquer complètement le nouveau thème.",
        "restart_now": "Redémarrer maintenant",
        "later": "Plus tard",
        "ok": "OK",
        "select_item_hint": "Sélectionnez un article pour voir les détails",
        "no_data": "Aucune donnée disponible",
        "top_selling_title": "Meilleures ventes (Qté)",
        "most_profitable_title": "Plus rentable",
        "search_placeholder": "Rechercher un produit...",
        "my_clients": "Mes Clients",
        "credit": "Crédit",
        "add_customer": "Ajouter Client",
        "customer_name": "Nom du Client",
        "customer": "Client",
        "sell_on_credit": "Vente à Crédit",
        "unpaid": "Impayé",
        "paid": "Payé",
        "debt_details": "Détails de la Dette",
        "confirm_credit_sale": "Confirmer la Vente à Crédit",
        "pay": "Payer",
        "phone": "Téléphone",
        "status": "Statut",
        "refilled": "Stock Réapprovisionné",
        "low_stock": "Stock Faible",
        "bar_chart": "Histogramme",
        "line_chart": "Courbe",
        "revenue_chart": "Statistiques des Revenus",
        "profit_chart": "Statistiques des Profits",
    },
    "en": {
        "sales": "Sales",
        "products": "Products",
        "analytics": "Analytics",
        "notifications": "Alertes",
        "settings": "Settings",
        "pos": "Point of Sale",
        "barcode_scan": "Barcode / Product Name",
        "search": "Search",
        "scan_hint": "Connect barcode scanner and scan — or type name/barcode manually",
        "recent_sales": "Recent Sales Today",
        "time": "Time",
        "product": "Product",
        "quantity": "Qty",
        "price": "Price",
        "total": "Total",
        "profit": "Profit",
        "scan_product": "Scan product barcode or search by name",
        "category": "Category",
        "barcode": "Barcode",
        "sell_price": "Sell Price",
        "stock": "Stock",
        "piece": "pc",
        "qty_label": "Qty:",
        "empty_stock": "Stock Empty",
        "confirm_sale": "Confirm Sale",
        "not_found": "Product not found",
        "choose_product": "Choose product:",
        "error": "Error",
        "invalid_qty": "Enter valid quantity",
        "sale_error": "Sale Error",
        "product_added": "Product added successfully",
        "barcode_exists": "Barcode already in use",
        "product_updated": "Product updated",
        "product_deleted": "Product deleted",
        "product_name_req": "Name is required",
        "data_error": "Data Error",
        "success": "Success",
        "selled": "Selled",
        "admin_mode": "Admin Mode",
        "user_mode": "User Mode",
        "switch_to_admin": "Switch to Admin",
        "switch_to_user": "Switch to User",
        "enter_password": "Enter password",
        "password": "Password",
        "cancel": "Cancel",
        "wrong_password": "Incorrect password",
        "current_account": "Current Account",
        "admin": "Admin",
        "user": "Seller",
        "dark": "Dark",
        "light": "Light",
        "alerts": "Products need restocking",
        "settings_title": "Settings",
        "appearance": "Appearance",
        "theme_mode": "Mode:",
        "account_settings": "Account Data",
        "shop_name_label": "Shop Name",
        "currency_label": "Currency",
        "low_stock_label": "Low Stock Alert",
        "account_type": "Account Type",
        "language": "Language",
        "save_settings": "Save Settings",
        "about_program": "About",
        "program_name": "POS Management System",
        "version": "Version 1.0",
        "appearance_saved": "Appearance",
        "appearance_hint": "Mode will apply on restart",
        "settings_saved": "Success",
        "settings_saved_msg": "Settings saved",
        "password_required": "Required",
        "admin_password": "Admin Password",
        "change_password": "Change Password",
        "current_password_label": "Current Password *",
        "new_password_label": "New Password *",
        "confirm_password_label": "Confirm New Password *",
        "wrong_current_password": "Current password is incorrect",
        "passwords_dont_match": "Passwords don't match",
        "password_changed": "Password changed",
        "admin_restricted": "Admin access required",
        "manage_products": "Manage Products",
        "add": "Add",
        "edit": "Edit",
        "delete": "Delete",
        "clear": "Clear",
        "clear_logs": "Clear Logs",
        "save": "Save",
        "back": "Back",
        "confirm": "Confirm",
        "product_data": "Product Data",
        "name_label": "Name *",
        "barcode_label": "Barcode",
        "category_label": "Category",
        "buy_price_label": "Buy Price *",
        "sell_price_label": "Sell Price *",
        "quantity_label": "Quantity *",
        "min_stock_label": "Min Stock",
        "buy_price": "Buy Price",
        "confirm_delete": "Confirm Delete",
        "delete_product_confirm": "Delete this product?",
        "select_product_first": "Select a product first",
        "alert": "Alert",
        "year": "Year:",
        "refresh": "Refresh",
        "export_pdf": "Export PDF",
        "today_revenue": "Today's Revenue",
        "today_profit": "Today's Profit",
        "month_revenue": "Month Revenue",
        "month_profit": "Month Profit",
        "total_products": "Total Products",
        "analytics_title": "Analytics & Charts",
        "matplotlib_missing": "matplotlib not installed",
        "reportlab_missing": "reportlab not installed",
        "install_hint": "pip install reportlab --break-system-packages",
        "save_report": "Save Report",
        "report_exported": "Report exported",
        "report_error": "Error",
        "report": "Report",
        "delete_year": "Delete Year Data",
        "delete_year_confirm": "Do you want to delete all sales for this year?",
        "admin_required": "Admin Access Required",
        "barcode_placeholder": "Enter barcode here...",
        "confirm_delete_sale": "Are you sure you want to undo this sale? (Stock will be restored)",
        "accent_color_label": "Accent Color:",
        "undo": "Undo Sale",
        "delete_sale_confirm": "Do you want to delete this sale from history only? (Stock will NOT be restored)",
        "add_to_cart": "Add to Cart",
        "cart_title": "Shopping Cart",
        "empty_cart": "Cart is empty",
        "confirm_bulk_sale": "Confirm Sale",
        "clear_cart_btn": "Clear Cart",
        "restart_required": "Restart Required",
        "restart_msg": "Please restart the application to apply the new theme completely.",
        "restart_now": "Restart Now",
        "later": "Later",
        "ok": "OK",
        "select_item_hint": "Select an item to view details",
        "no_data": "No data available yet",
        "top_selling_title": "Top Selling (Qty)",
        "most_profitable_title": "Most Profitable",
        "search_placeholder": "Search product...",
        "my_clients": "My Clients",
        "credit": "Credit",
        "add_customer": "Add Customer",
        "customer_name": "Customer Name",
        "customer": "Customer",
        "sell_on_credit": "Sell on Credit",
        "unpaid": "Unpaid",
        "paid": "Paid",
        "debt_details": "Debt Details",
        "confirm_credit_sale": "Confirm Credit Sale",
        "pay": "Pay",
        "phone": "Phone Number",
        "status": "Status",
        "refilled": "Stock Refilled",
        "low_stock": "Low Stock",
        "bar_chart": "Bar Chart",
        "line_chart": "Line Chart",
        "revenue_chart": "Yearly Revenue Stats",
        "profit_chart": "Yearly Profit Stats",
    },
}


def get_text(key, lang="ar"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["ar"]).get(key, key)
